default: &default
  title: 答小晶daxiaojing.top—服务平台
  qiniu:
    base_url: 'http://ovlh8eznz.bkt.clouddn.com/'
    preview_size: '?imageView/2/w/100'
    preview_md_size: '-jyf'
    preview_lg_size: '?imageView/2/w/600'
    preview_thumbnail_size: '?imageMogr2/thumbnail/480x360'
    trial_car_default_image: 'trial_car_default.png'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default